name: Build WASM Core

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-wasm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: wasm32-unknown-unknown

      - name: Run Rust tests
        run: cargo test --manifest-path core/wasm/Cargo.toml
        
      - name: Install wasm-pack
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-pack

      - name: Build WASM for Node.js
        run: |
         wasm-pack build core/wasm \
          --target nodejs \
          --release \
          --out-dir ../../api/wasm

      - name: Install API dependencies
        working-directory: api
        run: npm install
      
      - name: Run API tests
        working-directory: api
        run: npm test
